src/script/__tests/Spend.test.ts
src/script/templates/P2PKH.ts
src/transaction/Transaction.ts

Added a way to validate the scripts within a transaction graph without access to a block headers client.

Script-only validation

---

src/primitives/Hash.ts
src/primitives/PrivateKey.ts
src/primitives/PublicKey.ts
src/primitives/__tests/ECDSA.test.ts
src/primitives/__tests/HMAC.test.ts
src/primitives/__tests/Hash.test.ts

The significant change is to the hash classes / functions in regard to the enc (encoding) input argument.
This started from an incorrect comment on PublicKey.verify that the default encoding was 'hex' when it is in fact 'utf8'.
Following this into the hash classes it turned out that the same enc input parameter was being used to determine both the encoding of the input message (msg) AND the desired output type (number[] vs hex string).
As this needed resolving in any case, and it looked like very few tests were passing 'hex' encoding. This PR proposes to resolve the issue by:
1.  using the input enc parameter only for msg encoding
2. add an explicit 'utf8' option where missing on the type of the enc parameter
3. add an explicit `digestHex()` method to mirror `digest()` when a hex string …

Hash enc digest hex

---

src/primitives/BigNumber.ts
src/primitives/PrivateKey.ts
src/primitives/__tests/bug-31.test.ts

Changes to resolve two issues reported by sirdeggen ini BUG #31 
1. Default PrivateKey constructor now forces its input value, however provided, to the curve by applying mod N.
2. toWif method now forces binary value to 32 BE bytes before base 58 encoding.
Additional details:
The PrivateKey constructor now has an additional optional argument `modN` which controls the "in curve field" limiting behavior.
The options are:
- 'apply': the default, apply modN to input to guarantee a valid PrivateKey.
- 'error': if input is out of field throw Error('Input is out of field').
- 'nocheck': assumes input is in field or will become so prior to use as a private key.
The toWif method checks that the BigNumber value is in field and throws an error if not.

Tone bug 31

---

src/primitives/utils.ts

Simple change that resolves max stack size error when using OP_PUSHDATA4 sized script values.

push(...x) fails for large array x values

---

src/script/templates/P2PKH.ts

Resolves:
```javascript
import { PrivateKey, P2PKH, } from '@bsv/sdk'
function getLockingScriptFromPrivateKey (privateKey) {
const script1 = new P2PKH().lock(privateKey.toPublicKey().toHash())
const script2 = new P2PKH().lock(privateKey.toAddress())
console.log({
script1: script1.toHex(),
script2: script2.toHex(),
})
console.log(script1.toHex() === script2.toHex())
return new P2PKH().lock(privateKey.toPublicKey().toHash())
}
const p = PrivateKey.fromRandom()
getLockingScriptFromPrivateKey(p)
```

[fix] length must be that of the data, not the original argument.

---

README.md
package.json

Apparently the correct term is Software Development Kit, although “Standard Development Kit” is a common mistake.

controversial stuff

---

src/primitives/Signature.ts

Compact sigs require 32 bytes for r and s values. This is already checked in fromCompact, but was previously not explicitly set in toCompact, leading to some small signatures for randomly low r or s values.

[fix] Enforce signature length in compact sigs

---

docs/examples/EXAMPLE_HD_WALLETS.md
src/compat/HD.ts
src/compat/__tests/HD.test.ts

HD class was not aligned with the rest the rest of the code.
It is counterintuitive to first create a new instance, then use factory method,
especially as there was already one static factory method.
What I propose is to add corresponding static factory method for each method `fromX` and use them in examples and tests.
Whats more, I made a small rearrangement of the methods to have all those factory methods next to each other.

refactor: add more static factory methods to HD class and use them in examples

---

src/script/OP.ts

The line above does exactly the same thing (reverse index) because JavaScript automatically converts keys of objects to strings.

[chore] remove redundant line

---

src/transaction/Transaction.ts
src/transaction/__tests/Transaction.test.ts

```
/**
* Since the validation of blockchain data is atomically transaction data validation,
* any application seeking to validate data in output scripts must store the entire transaction as well.
* Since the transaction data includes the output script data, saving a second copy of potentially
* large scripts can bloat application storage requirements.
* 
* This function efficiently parses binary transaction data to determine the offsets and lengths of each script.
* This supports the efficient retreival of script data from transaction data.
* 
* @param bin binary transaction data
* @returns {
*   inputs: { vin: number, offset: number, length: number }[]
*   outputs: { vout: number, offset: number, length: number }[]
* }
*/
static parseScriptOffsets(bin: number[])
```

Add Transaction.parseScriptOffsets

---

src/primitives/PublicKey.ts
src/primitives/Signature.ts

Thanks Zan from Rock Wallet / nChain team for the patch.
There were a few missing Mod N operations which meant some signatures recovered the incorrect pubkey.

[fix] Compact SIgnatures Pubkey Recovery function precision.

---

docs/primitives.md
src/primitives/PrivateKey.ts
src/primitives/PublicKey.ts

A slight improvement to the API, allows string prefixes like 'testnet' on `privateKey.toAddress()` and `publicKey.toAddress()` methods.
Allows prefixes 'mainnet', 'testnet' and also the shorthand 'main' and 'test' to indentify the network.
Although the use of [0x6f] prefix is well documented, this makes the code less cryptic to read and write, works like the old bsv library, also included shorthand 'main' and 'test' as they are the network identifiers used in WhatsOnChain.

toAddress() string prefix support

---

docs/transaction.md
src/script/templates/P2PKH.ts
src/transaction/Transaction.ts
src/transaction/TransactionInput.ts
src/transaction/__tests/Transaction.test.ts

In my apps I usually work with UTXOs and keep them stored and recycle them etc.
This additional field `sourceSatoshis` on inputs allows for fee calculation to not require the source transaction anymore.
This allows to create transactions and calculate fees solely using UTXOs (for example fetched from WoC), I included an example in `Transactions.test.ts` file. 
Edit 
* I since added a utility method `getFee()` to transactions that returns the current tx fee.
* Also added support for input.sourceSatoshis on P2PKH.unlock() method

Addional input field sourceSatoshis to be used in fee calculation

---

src/transaction/broadcasters/__tests/ARC.test.ts
src/transaction/http/FetchHttpClient.ts
src/transaction/http/NodejsHttpClient.ts

Responses from latest version of ARC weren't parsed properly because their returned content-type header is `application/json; charset=UTF-8` and ts-sdk was only checking for `=== 'application/json'`
This resulted in an incorrect return value for `tx.broadcast()` when using the default broadcaster:
```js
{ status: 'success', txid: undefined, message: 'undefined undefined' }
```

Improve JSON content type detection

---

CHANGELOG.md
package-lock.json
package.json
src/primitives/Hash.ts

In `4-chain` team we've been trying to use `ts-sdk` along with [spv-wallet-js-client](https://github.com/bitcoin-sv/spv-wallet-js-client) for `react-native` **mobile application**.
We faced an issue with `Buffer` during `xPriv` creation:
```
[ReferenceError: Property 'Buffer' doesn't exist]
```
We discovered that when we call `mnemonic.toSeed()`, the function`pbkdf2` is internally called. 
And right here in the `pbkdf2` function we've found an unnecessary `Buffer.from` call that creates an unused local variable `s`.
After commented out this line locally - the entire functionality began working on mobile device.

removed unnecessary Buffer.from in pbkdf2

---

CHANGELOG.md
src/compat/Utxo.ts
src/transaction/Transaction.ts

When using `Utxo.fromUtxo`, sourceTXID was not being set. This causes cascading issue when trying to sign a transaction, serialize it, or calculating fees. I've included two updates. 
1. `Utxo.fromUtxo` now sets `sourceTXID` on the input it returns.
2. `Transaction.toBinary` and `Transaction.verify` now check first if a sourceTXID is populated and uses that before falling back to `sourceTransaction.id()`/`sourceTransaction.hash()`

fix sourceTXID as default

---

.github/workflows/push.yaml

Attempt to resolve error in publishing:
https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions

Update push.yaml to use v3 for publish

---

CHANGELOG.md
docs/primitives.md
src/primitives/Point.ts
src/primitives/PublicKey.ts
src/primitives/__tests/PublicKey.test.ts

Changes type of response from toDER. Could have far reaching consequences. Please review.
If your code previously did this:
```js
const pubkey = key.toPublicKey().toDER()
```
Then you need to update to:
```js
const pubkey = key.toPublicKey().toString()
// OR
const pubkey = key.toPublicKey().toDER('hex')
```
You no longer have to do this to get the number array -- as it wastes clock cycles doing this conversion back and forth.
```js
Utils.toArray(key.toPublicKey().toDER(), 'hex')
```
Closes [Issue 110](https://github.com/bitcoin-sv/ts-sdk/issues/110)

[ Change ] pubkey.toDER() defaults to number[] rather than string

---

src/transaction/Broadcaster.ts
src/transaction/broadcasters/ARC.ts

Added `competingTxs` to `BroadcastResponse`, they are sent if double spend was attempted.
#ARCO-142

ARCO-142: add competing txs to broadcast response

---

CHANGELOG.md
package-lock.json
package.json
src/compat/ECIES.ts
src/compat/__tests/ECIES.test.ts

Remove the explicit null check to allow undefined fromPrivateKey in electrumEncrypt, and use the same style to omit fromPublicKey in electrumDecrypt. Aligns with existing style in bitcoreEncrypt as well.
Does not impact tests.
- Doing this makes some change not related to this pr so I didn't commit the results, and there are existing unrelated lint errors

allow omitting fromPrivateKey for ephemeral key in electrumEncrypt

---

docs/transaction.md
package-lock.json
package.json
src/transaction/Beef.ts
src/transaction/BeefTx.ts

Updates Beef and BeefTx classes to implement proposed BRC96 serialization format.
Implementation favors compatibility with V1 specification: Default constructed Beef serializes to V1 unless a V2 feature (txid only transaction) is used.

Beef implement BRC96 V2 serialization

---

CHANGELOG.md
package-lock.json
package.json
webpack.config.js

This PR updates the build process to ensure support for various environments such as a static html site, or Postman pre-request scripts.
- Added UMD bundling using Webpack, which generates bundle.js in dist/umd/.
- Updated package.json to export dist/umd/bundle.js.
- The build script now runs both TypeScript and Webpack build processes.
Closes #47 

UMD support for non-standard environments

---

CHANGELOG.md
package-lock.json
package.json
src/compat/ECIES.ts
src/compat/__tests/ECIES.test.ts

In the electrumDecrypt function, the following modifications were made:
- The function now checks for both compressed (33 bytes) and uncompressed (65 bytes) public keys by examining the first byte:
- If the first byte is 0x02 or 0x03, it identifies a compressed public key (33 bytes).
- If the first byte is 0x04, it identifies an uncompressed public key (65 bytes).
- The offset is then adjusted based on the actual length of the public key extracted. This ensures that the subsequent slicing of the ciphertext and HMAC is accurate, preventing errors during decryption.
- These changes address issues where decryption would fail with errors like "Invalid ciphertext length" or "buf length must be a multiple of 4".
Closes #124 
Create a test case based on example use-case which was previously …

ECIES ElectrumDecrypt Bug Fix

---

CHANGELOG.md
docs/overlay-tools.md
package-lock.json
package.json
src/overlay-tools/LookupResolver.ts
src/overlay-tools/SHIPBroadcaster.ts
src/overlay-tools/__tests/LookupResolver.test.ts
src/overlay-tools/__tests/SHIPBroadcaster.test.ts

Added support for Overlay broadcast and lookup timeouts.

Lookup timeouts

---

CHANGELOG.md
docs/wallet.md
package-lock.json
package.json
src/wallet/Wallet.interfaces.ts

- revealSpecificKeyLinkage requires a counterparty. 
- ProtoWallet now correctly implements the wallet interface.
When using the ProtoWallet as param which required a Wallet, there was an error thrown that it didn't properly implement the interface. This was caused by a discrepancy in the revealSpecificKeyLinkage function counterparty arg.

Key linkage args fix

---

CHANGELOG.md
package-lock.json
package.json
src/primitives/PublicKey.ts
src/primitives/__tests/PublicKey.test.ts

Stop people from accidentally using the public key constructor when they should use `.fromString()`.
This leads to corrupted public keys but does not throw errors until later. Better to throw here, immediately, and with a clear resolution to the problem.

Pubkey gotcha

---

CHANGELOG.md
docs/transaction.md
package-lock.json
package.json
src/transaction/ChainTracker.ts
src/transaction/MerklePath.ts
src/transaction/__tests/MerklePath.test.ts
src/transaction/chaintrackers/WhatsOnChain.ts
src/transaction/chaintrackers/__tests/WhatsOnChainChainTracker.test.ts

- new method on the interface for ChainTrackers which returns the current height of the blockchain.
- Implemented a Coinbase specific MerklePath .verify conditional block which ensures the input is spendable if it's a coinbase output.
[Discussion - 90](https://github.com/bitcoin-sv/BRCs/discussions/90)

[ Feature ] Coinbase MerklePath verification.

---

package-lock.json
package.json
src/transaction/Transaction.ts

The `<= 0` satoshis check should be a `< 0` satoshis check because 0 sat outputs are allowed.

[ FIX ] off by one sats check when adding an output.

---

CHANGELOG.md
docs/auth.md
package-lock.json
package.json
src/auth/Peer.ts

By persisting the last-interacted-with peer, we can avoid unnecessary handshakes without requiring application code to track peer identity keys when only one foreign peer exists over a given transport.
Support for talking to multiple peers, or broadcasting for anyone, over a transport is still maintained, because you can still specify a foreign identity key in the `.toPeer()` call. However, rather than assuming a new session needs to be started by default, we now assume, if a previous interaction has occurred, that messages are destined for the same recipient.
None

Last Session Persistence

---

CHANGELOG.md
package-lock.json
package.json
src/auth/certificates/Certificate.ts
src/wallet/substrates/__tests/WalletWire.integration.test.ts

Unnecessary length byte can be dropped. BREAKING CHANGE (from 1.2.22)

[OPINION] drop the length byte on certificate signatures

---

CHANGELOG.md
package-lock.json
package.json
src/wallet/ProtoWallet.ts

Reverting use of `instanceof` in ProtoWallet's constructor — in real environments, this check is not reliable and will fail too often. The `identityKey` check does the trick, since PrivateKeys and strings never have this property, while `KeyDeriver`s always do, and those are the only two types to disambiguate.

Instanceof revert

---

CHANGELOG.md
docs/auth.md
docs/wallet.md
package-lock.json
package.json
src/auth/certificates/Certificate.ts
src/auth/certificates/MasterCertificate.ts
src/auth/certificates/VerifiableCertificate.ts
src/auth/certificates/__tests/VerifiableCertificate.test.ts
src/wallet/ProtoWallet.ts

Anywhere that _only_ cryptographic operations are needed, a wallet implementing the WalletInterface should be able to be used.
A ProtoWallet is defined as "a precursor to a full wallet, capable of performing all foundational cryptographic operations."
To support use-cases that only require a ProtoWallet but might be passed a WalletInterface type, I have modified ProtoWallet to make the KeyDeriver optional, and to allow an optional originator argument on each supported method.
- [x I have updated `CHANGELOG.md` with my changes

All wallets are protowallets

---

CHANGELOG.md
package-lock.json
package.json
src/wallet/substrates/HTTPWalletJSON.ts

Added a error throw to the HTTPWalletJSON.ts

wallet error handling

---

CHANGELOG.md
docs/transaction.md
package-lock.json
package.json
src/transaction/chaintrackers/WhatsOnChain.ts

Change
- Make URL, httpClient, getHttpHeaders protected instead of private to support extending WhatsOnChain class.
With this change, wallet-toolbox can extend sdk's WhatsOnChain to add support for additional methods, packaged
the way it requires for compatibility with other service providers.

Whats on chain extend

---

CHANGELOG.md
package-lock.json
package.json
src/primitives/Hash.ts

Picked up when running tsc in a project
I think this just returns the wrong type. Simple fix.
```
tsc
node_modules/@bsv/sdk/dist/types/src/primitives/Hash.d.ts:206:5 - error TS2416: Property '_digestHex' in type 'SHA512' is not assignable to the same property in base type 'BaseHash'.
Type '() => number[]' is not assignable to type '() => string'.
Type 'number[]' is not assignable to type 'string'.
206     _digestHex(): number[];
```

[ FIX ] Hash.SHA512._digestHex return type

---

CHANGELOG.md
docs/overlay-tools.md
docs/script.md
package-lock.json
package.json
src/script/templates/PushDrop.ts

PushDrop needs originator support to work with certain protocols in secure admin-only contexts. This is added as an optional second constructor parameter.

Pushdrop originators

---

CHANGELOG.md
docs/auth.md
package-lock.json
package.json
src/auth/clients/AuthFetch.ts

Use the first output index in AuthFetch for outgoing payments, and persist payee derivation details in custom instructions.

Fix AuthFetch payments

---

CHANGELOG.md
package-lock.json
package.json
src/overlay-tools/SHIPBroadcaster.ts
src/overlay-tools/__tests/SHIPBroadcaster.test.ts

Extended a SHIP broadcast timeout to accommodate for high latency / mobile internet connections.

Fix SHIP Broadcast Timeouts

---

CHANGELOG.md
docs/wallet-substrates.md
docs/wallet.md
package-lock.json
package.json
src/wallet/Wallet.interfaces.ts
src/wallet/substrates/WalletWireProcessor.ts
src/wallet/substrates/WalletWireTransceiver.ts
src/wallet/substrates/window.CWI.ts

Adds action status 'failed' which is the result of abortAction.
Wallet wire updated. This does not alter the bytes, just adds support for a new byte value mapped to 'failed'
All tests pass.
Docs and CHANGELOG updated.

Add action status failed

---

CHANGELOG.md
package-lock.json
package.json
src/auth/clients/AuthFetch.ts
src/auth/transports/SimplifiedFetchTransport.ts

Sorts AuthFetch request and response headers by key before serialization to ensure a consistent order for signing and verification.
Fixes signature verification errors that were found during integration testing where a bsv-payment was provided in response to a 402 error. The server would try to verify the request signature, but would fail because it was not correctly ordering request headers.
- [] I have made corresponding changes to the documentation

Ensure consistent ordering of request/response headers

---

CHANGELOG.md
docs/kvstore.md
docs/wallet.md
package-lock.json
package.json
src/kvstore/LocalKVStore.ts
src/kvstore/__tests/LocalKVStore.test.ts
src/wallet/WERR_REVIEW_ACTIONS.ts
src/wallet/Wallet.interfaces.ts
src/wallet/WalletError.ts
src/wallet/index.ts
src/wallet/substrates/HTTPWalletJSON.ts

tests pass, linted, doc, version 1.4.18, changelogged
Updated LocalKVStore
Added support for WERR_REVIEW_ACTIONS, an error thrown when createAction in immediate (non-delayed) mode encounters issues broadcasting new transactions (doubleSpend, invalidTx, serviceError/Unavailable).

Local k vtweaks

---

benchmarks/bignumber-bench.js
docs/performance.md
src/primitives/BigNumber.ts

- create a simple benchmark script for huge numbers
- document benchmark results
- optimise `mul`, `imul`, `sqr`, `isqr`, and `mulTo` to avoid extra signed conversions
- `npm test`

Improve BigNumber multiplication

---

benchmarks/serialization-bench.js
docs/performance.md
src/primitives/BigNumber.ts

- implement serialization benchmarks
- optimize BigNumber fromSm, toSm, and fromScriptNum
- document performance gains for 200k-digit script number operations
- `npm test`
- `node benchmarks/serialization-bench.js 200000 1`

Optimize script number serializers

---

src/primitives/BigNumber.ts
src/script/Spend.ts

- fix strict-boolean lint issues in BigNumber
- ensure case blocks in Spend use braces
- add fallthrough comment for NOP opcodes
- `npm run lint:ci`
- `npm test`

Resolve lint issues in BigNumber and Spend

---

benchmarks/symmetric-key-bench.js
docs/performance.md
src/primitives/AESGCM.ts

- add a SymmetricKey benchmark covering large, medium and small payloads
- speed up AESGCM internals by avoiding excess allocations
- document SymmetricKey benchmark results
- `npm test`
- `node benchmarks/symmetric-key-bench.js`

Add AESGCM optimizations and benchmark

---

CHANGELOG.md
package-lock.json
package.json
src/wallet/substrates/HTTPWalletJSON.ts

Using origin !== “file://“ filters out ides which run esm node so they’re not falsely detected as browsers.
Also actively setting a header: Originator as well as Origin. Metanet desktop is expect that to be set.
Closes #303

[ FIX ] add origintor when in node.js env.

---

README.md
mkdocs.yml
src/transaction/Beef.ts

fixes broken `https://github.com/bitcoin-sv/ts-sdk` links 
by replacing `bitcoin-sv` with `bsv-blockchain` in links.
---
Previous behavior:
User clicked
User got

update github repo path

---

CHANGELOG.md
docs/reference/auth.md
docs/reference/messages.md
docs/reference/overlay-tools.md
docs/reference/primitives.md
docs/reference/script.md
package-lock.json
package.json
src/primitives/PrivateKey.ts

Added some safety checks to the PrivateKey.toKeyShares(m, n) function which can be used to split a key into shamir shares in order to securely back it up. Namely, check each point isn't at x = 0 (because the y coordinate would be the key itself) and make sure that no two shares are alike, otherwise you could get into a situation where you cannot recover the key.
Closes #334

[ TOB-BSV-2 ]‬ ‭toKeyShares‬‭ can result in key leakage or unrecoverable‬‭ keys‬

---

src/transaction/Transaction.ts

Fix SPV verification logic to properly handle invalid merkle path validation. MerklePath.verify() returns false when validation fails (not an error), but the previous logic treated this as a fallback to input verification instead of a failure case. Invalid merkle paths now throw error immediately.
None

Fix SPV verification to handle invalid merkle paths properly

---

CHANGELOG.md
docs/reference/identity.md
docs/reference/storage.md
package-lock.json
package.json
src/identity/IdentityClient.ts
src/identity/__tests/IdentityClient.test.ts

- Supports overriding identity resolution results with personal contacts in IdentityClient.discoverByIdentityKey and IdentityClient.discoverByAttributes. 
- A overrideWithContacts parameter allows returning pure overlay results when needed.
- Maintains backward compatibility while improving search performance and user experience.
8 new comprehensive test cases covering all edge cases

Enhanced Identity Resolution
