- src/primitives/BigNumber.ts
- src/primitives/PrivateKey.ts
- src/primitives/index.ts
- src/primitives/utils.ts
Allows PrivateKey to be constructed directly from BigNumber.
> Allow BigNumber constructor to accept a BigNumber.

- docs/examples/EXAMPLE_SIMPLE_TX.md
- docs/script.md
- src/script/Script.ts
- src/script/__tests/Script.test.ts
- src/script/templates/P2PKH.ts
Thanks to @rohenaz for pointing out the missing function.
> [feature] helper function to allow Address => Locking Script

- src/script/templates/P2PKH.ts
Cleanup issues with inputs using sourceTXID vs sourceTransaction.
Extend unlock to sign inputs without sourceTransaction, using just lockingScript.
> Avoid requiring sourceTransaction on inputs.

- docs/concepts/42.md
- docs/concepts/BEEF.md
- docs/concepts/CHAIN_SPV.md
- docs/concepts/FEE.md
- docs/concepts/HASHES.md
- docs/concepts/HOW_TX.md
- docs/concepts/OP.md
- docs/concepts/README.md
- docs/concepts/TEMPLATES.md
- docs/concepts/TX_SIG.md
- docs/concepts/TX_VALID.md
The high-level, conceptual documentation for the library has been completed.
> Concept-level documentation

- src/script/Script.ts
Fixes https://github.com/bitcoin-sv/ts-sdk/issues/42
FAO @zhfnjust
> [fix] adding startsWith OP_ seems to fix the ASM parsing bug

- docs/examples/EXAMPLE_SIMPLE_TX.md
- src/transaction/broadcasters/ARC.ts
- src/transaction/broadcasters/DefaultHttpClient.ts
- src/transaction/broadcasters/HttpClient.ts
- src/transaction/broadcasters/NodejsHttpClient.ts
- src/transaction/broadcasters/__tests/ARC.test.ts
- src/transaction/broadcasters/index.ts
> feat(#65): configure ARC with custom http client

- docs/examples/EXAMPLE_UTXOS_TX.md
Here is a documentation putting together some contributions I added and how I use the sdk to build TXs.
Its an example for newbies coming from old bsv library (my case) and shows how to do two common things: building a TX from UTXOs and building OP_RETURN scripts. 
I think this is handy example as it took me some time to figure out and I believe others do the same kind of operations.
As usual reject if you think its not up to date or not up to par or other reason, or let me know if it needs a more lengthy description etc.
Cheers,
> example-utxos-tx.md

- CHANGELOG.md
- package-lock.json
- package.json
- src/totp/totp.ts
remove debug console log from codebase
> [chore] remove debugging console log

- package-lock.json
- package.json
Updates package.json with correct version number for latest PR merge.
> Version patch 1.1.11

- CHANGELOG.md
- package-lock.json
- package.json
- src/primitives/TransactionSignature.ts
One more change missed in the previous PR to prioritize sourceTXID over sourceTransaction
> fix one more sourceTXID

- docs/primitives.md
- package-lock.json
- package.json
- src/primitives/PublicKey.ts
Incorrect type returned by toDER() by default just a missing commit from previous branch which was merged. No further changes, changelog already captures this behavior.
> [ FIX ] PubicKey.toDER()

- docs/primitives.md
- package-lock.json
- package.json
- src/primitives/PrivateKey.ts
Example was using a previous version of the method - ultimately this is not how we expect people to use the feature. Rather there is a fromBackupShares method which now has equivalent documentation which is the appropriate convenience function. possible that the other method should not be exported. room for discussion.
[Discord](https://discord.com/channels/953808129043333140/1278370706215796828) chat.
> [ FIX ] shamir example in the docs

- CHANGELOG.md
- docs/primitives.md
- docs/transaction.md
- package-lock.json
- package.json
- src/primitives/Curve.ts
- src/primitives/ECDSA.ts
- src/primitives/Point.ts
- src/primitives/TransactionSignature.ts
- src/primitives/utils.ts
- src/script/Spend.ts
- src/transaction/Transaction.ts
- src/transaction/TransactionInput.ts
- src/transaction/__tests/Transaction.benchmarks.test.ts
Optimize ECDSA verification time by utilizing BigInt primitives.
Added timing statements around signature verification.
Observed a reduction in time spent from 80 to 20 ms.
> 4x Optimize ECDSA verification time

- CHANGELOG.md
- docs/transaction.md
- package-lock.json
- package.json
- src/transaction/MerklePath.ts
- src/transaction/Transaction.ts
- src/transaction/__tests/Transaction.test.ts
Implemented BRC-95 Atomic BEEF, and added the ability to pull a particular TXID out of a BEEF.
None
> Atomic BEEF

- CHANGELOG.md
- docs/transaction.md
- package-lock.json
- package.json
- src/transaction/Beef.ts
- src/transaction/Transaction.ts
- src/transaction/__tests/Beef.test.ts
Beef.toBinaryAtomic(txid: string) to serialize Beef with AtomicBEEF header.
Transaction.fromAtomicBEEF
1. Test for all required dependencies was ignoring BUMP hashes.
2. Test for unused transactions required additional fix.
> Tone add Beef.toBinaryAtomic

- .github/workflows/push.yaml
- CHANGELOG.md
- docs/overlay-tools.md
- docs/wallet.md
- package-lock.json
- package.json
As a base-level dependency in all BSV projects, and as a cryptographic library that, itself, has no dependencies, we should ensure that we contribute to a secure software supply chain.
One great way to do this is to ensure that all package versions are built in a trusted environment, one that isn't as easy to compromise with malware.
NPM's new [package provenance](https://github.blog/security/supply-chain-security/introducing-npm-package-provenance/) features are easy to integrate and allow people who consume the library to more easily audit their software supply chains.
> NPM Package Provenance

- CHANGELOG.md
- docs/compat.md
- docs/messages.md
- docs/overlay-tools.md
- docs/primitives.md
- docs/script.md
- docs/totp.md
- docs/transaction.md
- docs/wallet.md
- package-lock.json
- package.json
- src/overlay-tools/SHIPBroadcaster.ts
- src/overlay-tools/__tests/SHIPBroadcaster.test.ts
Updated the default ShipBroadcast config, tests, and docs.
> Shipbroadcast update

- CHANGELOG.md
- docs/transaction.md
- package.json
- src/transaction/Broadcaster.ts
Exposed broadcastMany in the Broadcaster interface.
-
> Broadcast many interface

- CHANGELOG.md
- docs/swagger/swagger.yaml
- docs/transaction.md
- package-lock.json
- package.json
- src/primitives/__tests/PrivateKey.test.ts
- src/transaction/Transaction.ts
Updated the Swagger such that the whole API has fleshed out examples for arguments and expected response.
> [ CHORE ]: Improve swagger

- CHANGELOG.md
- docs/compat.md
- docs/primitives.md
- docs/transaction.md
- package-lock.json
- package.json
- src/primitives/BigNumber.ts
- src/primitives/PublicKey.ts
- src/primitives/Random.ts
- src/primitives/utils.ts
- src/totp/totp.ts
- src/transaction/Beef.ts
- src/transaction/BeefParty.ts
- src/transaction/BeefTx.ts
- src/transaction/Transaction.ts
- src/transaction/__tests/Beef.test.ts
- src/transaction/__tests/Transaction.benchmarks.test.ts
- src/transaction/__tests/Transaction.test.ts
- src/transaction/broadcasters/__tests/WhatsOnChainBroadcaster.test.ts
- Fixed a slice => splice error in Beef.
- A few small refactors to clarify code readability.
- I reverted the CHANGELOG link format because it's been wasting a bunch of time to link a bunch of stuff for every PR. Back to the simple way were we just link to the version and the things which changed are noted there. Added some historical context for minor version releases.
- Removed V1 Beef txidOnly
> [ CHORE ] refactored based on sonar lint feedback & [ BUG ] splice bug

- CHANGELOG.md
- docs/auth.md
- docs/overlay-tools.md
- docs/script.md
- docs/wallet-substrates.md
- docs/wallet.md
- package-lock.json
- package.json
- src/auth/Peer.ts
- src/auth/certificates/Certificate.ts
- src/auth/certificates/MasterCertificate.ts
- src/auth/certificates/VerifiableCertificate.ts
- src/auth/certificates/__tests/CompletedProtoWallet.ts
- src/auth/clients/AuthFetch.ts
- src/auth/utils/createNonce.ts
- src/auth/utils/getVerifiableCertificates.ts
- src/auth/utils/validateCertificates.ts
- src/auth/utils/verifyNonce.ts
- src/overlay-tools/OverlayAdminTokenTemplate.ts
- src/script/templates/PushDrop.ts
- src/wallet/ProtoWallet.ts
- src/wallet/Wallet.interfaces.ts
- src/wallet/WalletClient.ts
- src/wallet/__tests/ProtoWallet.test.ts
- src/wallet/substrates/HTTPWalletJSON.ts
- src/wallet/substrates/WalletWireProcessor.ts
- src/wallet/substrates/WalletWireTransceiver.ts
- src/wallet/substrates/XDM.ts
- src/wallet/substrates/__tests/WalletWire.integration.test.ts
- src/wallet/substrates/window.CWI.ts
These changes are intended to align with work being done in the Wallet Toolbox.
> ProtoWallet changes

- CHANGELOG.md
- docs/auth.md
- package-lock.json
- package.json
- src/auth/__tests/Peer.test.ts
- src/auth/certificates/Certificate.ts
- src/auth/certificates/MasterCertificate.ts
- src/auth/certificates/VerifiableCertificate.ts
- src/auth/certificates/__tests/MasterCertificate.test.ts
- src/auth/certificates/__tests/VerifiableCertificate.test.ts
- src/auth/utils/getVerifiableCertificates.ts
- src/auth/utils/validateCertificates.ts
Refactored certificate classes and helper functions based on usage requirements in the new acquireCertificate method via the issuance path.
> Certificate refactors

- CHANGELOG.md
- docs/auth.md
- docs/primitives.md
- docs/script.md
- docs/transaction.md
- docs/wallet-substrates.md
- docs/wallet.md
- package-lock.json
- package.json
- Fixed build issue, and conformed to ts-standard
> Version update

- CHANGELOG.md
- package-lock.json
- package.json
- src/overlay-tools/SHIPBroadcaster.ts
Fixed a reference error in SHIPBroadcaster
> Fix SHIPBroadcaster

- .github/workflows/push.yaml
- CHANGELOG.md
- docs/auth.md
- package-lock.json
- package.json
- src/auth/Peer.ts
- src/auth/SessionManager.ts
- src/auth/__tests/Peer.test.ts
- src/auth/__tests/SessionManager.test.ts
- src/auth/types.ts
Allow concurrent sessions to be managed with a single peer. Add a multi-device test case.
> Multi-session management with a single peer

- CHANGELOG.md
- package-lock.json
- package.json
- src/auth/clients/AuthFetch.ts
Session management is improved.
> Redo handshake if AuthFetch fails to find a session

- CHANGELOG.md
- docs/overlay-tools.md
- package-lock.json
- package.json
- src/overlay-tools/LookupResolver.ts
- src/overlay-tools/SHIPBroadcaster.ts
- src/overlay-tools/__tests/LookupResolver.test.ts
- src/overlay-tools/__tests/SHIPBroadcaster.test.ts
- src/overlay-tools/index.ts
- Support for the Babbage testnet SLAP tracker
- Support for overlay network presets for mainnet, testnet, or local
> Testnet slap

- CHANGELOG.md
- package-lock.json
- package.json
- src/auth/__tests/Peer.test.ts
- src/auth/clients/AuthFetch.ts
- src/auth/transports/SimplifiedFetchTransport.ts
- src/auth/utils/__tests/cryptononce.test.ts
- src/transaction/__tests/Transaction.benchmarks.test.ts
- webpack.config.js
Provide a brief description of the changes you've made.
> Resolve early for non initialRequest non general messages

- CHANGELOG.md
- docs/storage.md
- package-lock.json
- package.json
- src/overlay-tools/LookupResolver.ts
- src/overlay-tools/__tests/LookupResolver.test.ts
- src/storage/StorageDownloader.ts
- src/storage/StorageUploader.ts
- src/storage/__test/StorageDownloader.test.ts
Provide a brief description of the changes you've made.
> header and expiryTime checks

- CHANGELOG.md
- docs/transaction.md
- package.json
- src/script/Spend.ts
- src/transaction/Transaction.ts
- src/transaction/__tests/Transaction.test.ts
Stop resource exhaustion in script execution.
#203 
> [ FIX ] #203 Script Interpreter Memory Exhaustion

- CHANGELOG.md
- docs/auth.md
- docs/compat.md
- docs/identity.md
- docs/kvstore.md
- docs/messages.md
- docs/overlay-tools.md
- docs/primitives.md
- docs/registry.md
- docs/script.md
- docs/storage.md
- docs/totp.md
- docs/transaction.md
- docs/wallet.md
- src/transaction/broadcasters/Teranode.ts
- src/transaction/broadcasters/index.ts
- src/transaction/http/BinaryFetchClient.ts
- src/transaction/http/DefaultHttpClient.ts
- src/transaction/http/NodejsHttpClient.ts
- src/transaction/http/index.ts
Add a broadcaster for Teranode and a binaryHTTPClient. 
New code doesn't touch anything else and would only need an integration test which we can't publish right now (since Teranode isn't publicly accessible).
> [ FEATURE ] Add a broadcaster for Teranode and a binaryHTTPClient

- package-lock.json
- package.json
- src/wallet/WalletClient.ts
Addes option to explicitly set react-native as a substrate
> [ CHORE ] manually set react0native as a substrate

- src/auth/__tests/Peer.test.ts
- remove hardcoded timeout in peer tests
- add helper to wait for next general message
- `npx jest src/auth/__tests/Peer.test.ts`
- `npm test -- --runTestsByPath src/auth/__tests/Peer.test.ts`
> Speed up Peer.test

- src/primitives/BigNumber.ts
- add more docblocks in `BigNumber`
- `npm run lint`
- `npm test`
> Restore BigNumber docblocks

- docs/performance.md
- src/primitives/ECDSA.ts
- src/primitives/Hash.ts
> Revert "Optimize BigInt ECDSA and hex conversion"

- CHANGELOG.md
- package-lock.json
- package.json
- src/overlay-tools/LookupResolver.ts
- src/overlay-tools/SHIPBroadcaster.ts
In support of the Private Overlay architecture, we extend topic managers an lookup services with new, optional `offChainValues` and `context` types.
> Replace freeform with private overlays

- CHANGELOG.md
- package-lock.json
- package.json
- src/overlay-tools/LookupResolver.ts
- src/overlay-tools/SHIPBroadcaster.ts
- src/overlay-tools/__tests/SHIPBroadcaster.test.ts
- src/transaction/Transaction.ts
Off Chain Values are now fully supported in Overlay Services.
> Integrate Off Chain Values

- CHANGELOG.md
- docs/overlay-tools.md
- docs/primitives.md
- docs/transaction.md
- package-lock.json
- package.json
- src/transaction/chaintrackers/BlockHeadersService.ts
- src/transaction/chaintrackers/index.ts
Added a ChainTracker which relies on an instance of [Block Headers Service](https://github.com/bitcoin-sv/block-headers-service).
> [ FEATURE ] Block headers service chain tracker

- CHANGELOG.md
- docs/primitives.md
- package-lock.json
- package.json
- src/primitives/utils.ts
Updates how Negative value VarInts are handled throughout the stack.
Closes #241 
> [ FIX ] Handling of Signed VarInts

- src/wallet/substrates/WalletWireProcessor.ts
Fixing what looks like a typo. This was causing Signature to be excluded from Discovery result.
> Fix discover sig

- .github/workflows/docs.yml
Updating workflow file only, for mkdocs.
> add this dep

- CHANGELOG.md
- package-lock.json
- package.json
- src/overlay-tools/LookupResolver.ts
Added more to the default array of SLAP trackers.
> Slap trackers

- CHANGELOG.md
- docs/reference/wallet.md
- package-lock.json
- package.json
- src/wallet/Wallet.interfaces.ts
ListOutputsArgs offset changed to number, negative values sort newest first, newest output is offset -1.
> List out neg offset

- CHANGELOG.md
- docs/reference/overlay-tools.md
- package-lock.json
- package.json
- src/overlay-tools/LookupResolver.ts
- src/overlay-tools/__tests/LookupResolver.test.ts
Cache lookup resolver state for faster overlay operations.
> Lookup resolver caching

- src/wallet/substrates/WalletWireProcessor.ts
- src/wallet/substrates/WalletWireTransceiver.ts
Addresses [Issue#300](https://github.com/bsv-blockchain/ts-sdk/issues/300)
Provide a brief description of the changes you've made.
> Serialize Keyring and Verifier in ListCertificates

- CHANGELOG.md
- docs/reference/wallet.md
- package-lock.json
- package.json
- src/wallet/WalletClient.ts
Provide a brief description of the changes you've made.
> [ FEATURE ] HTTPS substrate & 20x speed increase of WalletClient initial connection
